- hosts: all
  tasks:
    - name: Update Red hat
      yum:
        name: "*"
        state: latest
      when: 
        ansible_os_family == "CentOS"
        or
        ansible_os_family == "RedHat"

    - name: Update Debian
      apt:  upgrade=safe  update_cache=true
      when: 
        ansible_os_family == "Debian"
        or
        ansible_os_family == "Ubuntu"

  become: true
